import type { TroubleshootingCategory } from "@shared/network-types";

export const troubleshootingCategories: TroubleshootingCategory[] = [
  {
    id: "connectivity",
    title: "Konektivitas Dasar",
    description: "Diagnosa masalah koneksi jaringan dasar",
    icon: "Network",
    steps: [
      {
        id: "check-physical",
        title: "1. Periksa Koneksi Fisik",
        description: "Pastikan kabel jaringan terhubung dengan benar atau WiFi sudah aktif.",
        troubleTip: "Cek lampu indikator pada port ethernet atau status WiFi di system tray.",
      },
      {
        id: "check-ip",
        title: "2. Verifikasi Konfigurasi IP",
        description: "Periksa apakah perangkat sudah mendapatkan IP address yang valid.",
        commands: ["ipconfig (Windows)", "ip addr (Linux)", "ifconfig (macOS)"],
        expectedResult: "Alamat IP yang valid (bukan 169.254.x.x untuk DHCP)",
        troubleTip: "Jika IP dimulai dengan 169.254, berarti DHCP server tidak merespons.",
      },
      {
        id: "ping-gateway",
        title: "3. Ping Default Gateway",
        description: "Test konektivitas ke router/gateway lokal.",
        commands: ["ping <gateway-ip>"],
        expectedResult: "Reply from gateway dengan latency < 5ms untuk jaringan lokal",
        troubleTip: "Jika timeout, kemungkinan ada masalah pada switch/router atau kabel.",
      },
      {
        id: "ping-dns",
        title: "4. Ping DNS Server",
        description: "Test konektivitas ke DNS server.",
        commands: ["ping 8.8.8.8", "ping 1.1.1.1"],
        expectedResult: "Reply from DNS server",
        troubleTip: "Jika gagal, masalah ada pada koneksi internet, bukan DNS resolution.",
      },
      {
        id: "dns-resolution",
        title: "5. Test DNS Resolution",
        description: "Verifikasi bahwa DNS dapat me-resolve domain names.",
        commands: ["nslookup google.com", "dig google.com"],
        expectedResult: "Menampilkan IP address dari domain yang di-query",
        troubleTip: "Jika gagal, coba ganti DNS server ke 8.8.8.8 atau 1.1.1.1",
      },
    ],
  },
  {
    id: "performance",
    title: "Performa Jaringan",
    description: "Diagnosa masalah kecepatan dan latency",
    icon: "Gauge",
    steps: [
      {
        id: "bandwidth-test",
        title: "1. Test Bandwidth",
        description: "Ukur kecepatan upload dan download.",
        commands: ["speedtest-cli", "fast.com (browser)"],
        expectedResult: "Kecepatan sesuai dengan paket internet yang dibeli",
        troubleTip: "Test di beberapa waktu berbeda untuk mengidentifikasi pola throttling.",
      },
      {
        id: "latency-check",
        title: "2. Cek Latency",
        description: "Ukur delay jaringan ke berbagai tujuan.",
        commands: ["ping -n 20 google.com", "ping -c 20 google.com"],
        expectedResult: "Latency stabil < 50ms untuk koneksi broadband",
        troubleTip: "Jitter tinggi (variasi latency) menunjukkan congestion.",
      },
      {
        id: "traceroute",
        title: "3. Traceroute",
        description: "Identifikasi hop mana yang menyebabkan delay.",
        commands: ["tracert google.com (Windows)", "traceroute google.com (Linux/macOS)"],
        expectedResult: "Setiap hop menampilkan latency yang reasonable",
        troubleTip: "Hop dengan * * * atau latency tinggi adalah bottleneck.",
      },
      {
        id: "packet-loss",
        title: "4. Deteksi Packet Loss",
        description: "Identifikasi apakah ada paket yang hilang.",
        commands: ["ping -n 100 <target> (Windows)", "ping -c 100 <target> (Linux/macOS)"],
        expectedResult: "0% packet loss",
        troubleTip: "Packet loss > 1% dapat menyebabkan masalah pada VoIP dan video call.",
      },
    ],
  },
  {
    id: "dns",
    title: "Masalah DNS",
    description: "Troubleshoot DNS resolution issues",
    icon: "Globe",
    steps: [
      {
        id: "flush-dns",
        title: "1. Flush DNS Cache",
        description: "Hapus cache DNS yang mungkin sudah kadaluarsa.",
        commands: [
          "ipconfig /flushdns (Windows)",
          "sudo dscacheutil -flushcache (macOS)",
          "sudo systemd-resolve --flush-caches (Linux)",
        ],
        expectedResult: "Cache berhasil dihapus",
        troubleTip: "Lakukan ini setelah mengubah DNS server.",
      },
      {
        id: "check-dns-config",
        title: "2. Verifikasi DNS Configuration",
        description: "Periksa DNS server yang sedang digunakan.",
        commands: ["nslookup", "cat /etc/resolv.conf (Linux)"],
        expectedResult: "DNS server yang valid terlist",
        troubleTip: "Gunakan public DNS seperti 8.8.8.8 atau 1.1.1.1 jika DNS ISP bermasalah.",
      },
      {
        id: "test-specific-dns",
        title: "3. Test dengan DNS Server Spesifik",
        description: "Query DNS server tertentu untuk membandingkan hasil.",
        commands: ["nslookup google.com 8.8.8.8", "dig @1.1.1.1 google.com"],
        expectedResult: "Response yang valid dari DNS server yang ditentukan",
        troubleTip: "Jika berhasil dengan DNS lain, masalahnya ada pada DNS default.",
      },
    ],
  },
  {
    id: "firewall",
    title: "Firewall & Security",
    description: "Diagnosa masalah akses yang diblokir",
    icon: "Shield",
    steps: [
      {
        id: "check-firewall-status",
        title: "1. Cek Status Firewall",
        description: "Periksa apakah firewall aktif dan rule apa yang berlaku.",
        commands: [
          "netsh advfirewall show allprofiles (Windows)",
          "sudo ufw status (Linux)",
          "sudo pfctl -sr (macOS)",
        ],
        expectedResult: "Firewall aktif dengan rules yang sesuai",
        troubleTip: "Nonaktifkan sementara untuk test (aktifkan kembali setelah selesai!).",
      },
      {
        id: "check-port",
        title: "2. Test Port Tertentu",
        description: "Verifikasi apakah port tertentu dapat diakses.",
        commands: [
          "telnet <host> <port>",
          "nc -zv <host> <port>",
          "Test-NetConnection <host> -Port <port> (PowerShell)",
        ],
        expectedResult: "Connection established/succeeded",
        troubleTip: "Jika gagal, port mungkin diblokir oleh firewall atau service tidak berjalan.",
      },
      {
        id: "check-listening",
        title: "3. Cek Port yang Listening",
        description: "Lihat service apa yang mendengarkan di port tertentu.",
        commands: ["netstat -an | find /i 'listening' (Windows)", "ss -tulpn (Linux)", "lsof -i -P | grep LISTEN (macOS)"],
        expectedResult: "Service yang diharapkan terlist pada port yang benar",
        troubleTip: "Jika port tidak listening, service mungkin tidak berjalan.",
      },
    ],
  },
  {
    id: "wireless",
    title: "Masalah WiFi",
    description: "Troubleshoot koneksi wireless",
    icon: "Wifi",
    steps: [
      {
        id: "check-wifi-status",
        title: "1. Cek Status WiFi Adapter",
        description: "Pastikan WiFi adapter aktif dan terdeteksi.",
        commands: ["netsh wlan show interfaces (Windows)", "iwconfig (Linux)", "airport -I (macOS)"],
        expectedResult: "Adapter terdeteksi dan connected ke network",
        troubleTip: "Coba disable/enable WiFi adapter jika tidak terdeteksi.",
      },
      {
        id: "scan-networks",
        title: "2. Scan Available Networks",
        description: "Lihat jaringan WiFi yang tersedia dan signal strength-nya.",
        commands: [
          "netsh wlan show networks mode=bssid (Windows)",
          "nmcli device wifi list (Linux)",
        ],
        expectedResult: "Network target terlihat dengan signal yang cukup",
        troubleTip: "Signal < 50% dapat menyebabkan disconnect dan slow speed.",
      },
      {
        id: "check-channel",
        title: "3. Analisis Channel Interference",
        description: "Identifikasi apakah ada interferensi dari jaringan lain.",
        commands: ["WiFi Analyzer app (Android/Windows)", "Wireless Diagnostics (macOS)"],
        expectedResult: "Channel yang digunakan tidak terlalu padat",
        troubleTip: "Ganti ke channel yang lebih sepi, atau gunakan 5GHz jika tersedia.",
      },
      {
        id: "forget-reconnect",
        title: "4. Forget dan Reconnect",
        description: "Hapus profil WiFi dan buat koneksi baru.",
        commands: ["netsh wlan delete profile name='NetworkName' (Windows)"],
        expectedResult: "Berhasil connect ulang dengan password baru",
        troubleTip: "Berguna jika password atau security settings berubah.",
      },
    ],
  },
];
